### ISSUE TITLE
plugin review for plugins.glpi-project.org

### ISSUE THREAD

**Issue by orthagh** [ericferon/glpi-webhook#1]
Hello @ericferon 

I review the plugin for your submission on plugin directory.

Here is some issues to fix to get an approval:

- the current screenshot url targets a 404 url
- the description invites the user to see the plugin wiki or readme for help, but both are not helpful
- the plugin is indicated to be functional on GLPI 10.0.x, but there is deprecated calls on installation and usage (check `files/_logs/php_errors.logs`)
- targets of notifications seems to be send only for your plugin statecheck, is it wanted ? events of core cannot be supported ?

additional remarks:
- Is there a way to customize the payload ?
- i see you added a `download_url` tag in your xml, are you interested by a publication on the GLPI marketplace ?

Regards

**Comment by ericferon** [comment]
I've fixed the different issues : 
- no screenshot anymore
- wiki has been created
- targets of notifications : all are supported, no limitation to statecheck only
If it's OK, you may publish it on the GLPI marketplace.
K.r,
