### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by gilbanech** [ericferon/glpi-webhook#10]
Thanks for the work you've done.
The plugin is trying to send a notification, but I am facing the following problem.
he does not want to log in to the api.
in the log I see the message:

cat /var/www/html/files/_log/webhook.log
2022-10-18 13:24:04 [9@glpi]
Error: call to URL https://mysite/api/v1/chat.postMessage failed with status 401, response {"status":"error","message":"You must be logged in to do this."}, curl_error , curl_errno 0

direct curl request works correctly:
curl -H "X-Auth-Token: My-Token-ID"
-H "X-User-Id: My-User-ID"
-H "Content-type:application/json"
https://mysite/api/v1/chat.postMessage
-d '{ "channel": "@user", "text": "This is a direct message!" }'
![webhook6](https://user-images.githubusercontent.com/76148833/196407683-a307233b-f3b7-4925-aa98-20686135533f.png)

P.S.
I dreamed of such a plugin for a very long time.
so I really appreciate your work!

**Comment by ericferon** [comment]
Hi,
Currently, the basic authentication sends a header "Authorization: Basic My-User-ID:My-Token-ID", but no "X-User-Id: My-User-ID" nor "X-Auth-Token: My-Token-ID".
K.r,

**Comment by gilbanech** [comment]
Hi,
Thank you.
I solved it with a little hack on a web proxy.
Thanks again for your plugin.
I hope you continue to develop it.
