### ISSUE TITLE
Webhook Error 400

### ISSUE THREAD

**Issue by sireskandar** [ericferon/glpi-webhook#11]
failed with status 400, response {"id":"model.incoming_hook.parse_data.app_error","message":"Unable to parse incoming data.","detailed_error":"","request_id":"t8rzm8qzaiyuxfxed5ckf5mz6r","status_code":400}, curl_error , curl_errno 0

**Comment by ericferon** [comment]
Hi,
With so little information, I cannot help you.
It seems that you reached the server, but with a wrong message.
K.r,
