### ISSUE TITLE
Error in auth when there are special characters in password

### ISSUE THREAD

**Issue by antonwantstosleep** [ericferon/glpi-webhook#13]
Hi!

If we set password to `&D` and get it with `$webhook_infos['additionnaloption']['secret']` => it will be `&#38;D`.

So, the base64 string for auth will be wrong.

We need to unescape html chars when creating the header.

In inc/notificationeventwebhook.class.php:

```
case 3: // Basic Authentication with base64 encoding
$headers = 
    [
        'Content-type: application/json',
        'Authorization: Basic '.base64_encode(htmlspecialchars_decode($webhook_infos['additionnaloption']['user']) .":".htmlspecialchars_decode($webhook_infos['additionnaloption']['secret']))
    ];
break;
```

**Comment by ericferon** [comment]
Hi,
Thank you very much for your contribution !
It has been included in v1.0.9.
K.r,
