### ISSUE TITLE
Special characters in webhook payloads not encoded properly

### ISSUE THREAD

**Issue by gljones2001** [ericferon/glpi-webhook#14]
When a webhook is created in GLPI and a notification template is used, something in the notification template translates text characters to URL encoding. For example, the character "<" becomes "%3C". Some webhook require these characters to be passed directly through, and this automatic encoding breaks this functionality.

An example:
Microsoft Teams has the ability using Webhooks to mention a user in a feed. The json looks like this (Example from [here](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html#user-mention-in-incoming-webhook-with-adaptive-cards)):

```json
{
    "type": "message",
    "attachments": [
        {
        "contentType": "application/vnd.microsoft.card.adaptive",
        "content": {
            "type": "AdaptiveCard",
            "body": [
                {
                    "type": "TextBlock",
                    "size": "Medium",
                    "weight": "Bolder",
                    "text": "Sample Adaptive Card with User Mention"
                },
                {
                    "type": "TextBlock",
                    "text": "Hi <at>Adele UPN</at>, <at>Adele Azure AD</at>"
                }
            ],
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "version": "1.0",
            "msteams": {
                "entities": [
                    {
                        "type": "mention",
                        "text": "<at>Adele UPN</at>",
                        "mentioned": {
                          "id": "AdeleV@contoso.onmicrosoft.com",
                          "name": "Adele Vance"
                        }
                      },
                      {
                        "type": "mention",
                        "text": "<at>Adele Azure AD</at>",
                        "mentioned": {
                          "id": "87d349ed-44d7-43e1-9a83-5f2406dee5bd",
                          "name": "Adele Vance"
                        }
                      }
                ]
            }
        }
    }]
}

```
As you can see, the <at> and </at> tags are required for the user mention to be passed through to Teams. These tags are being encoded into URL strings, and teams rejects the message because of this.

Apparently, there is a way to mitigate this. In GLPI there is a function you can run within the plugin system to undo the sanitization that is occurring in GLPI:

https://github.com/glpi-project/glpi/blob/78c83ac4a6e070c4f1b7c0294adadaafe84e8ac2/src/NotificationTemplate.php#L287-L288

as according to the folks at GLPI: https://github.com/glpi-project/glpi/issues/14162#issuecomment-1445815260

**Comment by ericferon** [comment]
Hi,
Thank you for your contribution.
I hope that I solved your problem in v1.0.10, but I cannot test it.
So, can you confirm ?
K.r,

**Comment by RogueSnipa** [comment]
Actually, I thought that this behavior was intended until today's version came out. :)
Yes, I can confirm that in the new version, strings like `<p>` have stopped turning into `&#60;p&#62;`.
Thank you so much for the wonderful plugin!

**Comment by gljones2001** [comment]
Yay! Thanks so much! I will update as soon as possible.
