### ISSUE TITLE
Bad Request error. v1.0.10 

### ISSUE THREAD

**Issue by RogueSnipa** [ericferon/glpi-webhook#15]
Sending a ticket description with two paragraphs leads to a Bad Request error

![image](https://user-images.githubusercontent.com/78896767/222661445-11b4c924-3565-410d-8458-aa58965ff9ba.png)

Ticket description source code:
```html
<p>1</p>
<p>2</p>
```
Notification template translation body
```json
{
"ID": "##ticket.id##",
"Events":"##ticket.action##",
"Locations":"##ticket.location##",
"Room Number":"##ticket.location.room##",
"Title":"##ticket.title##",
"Category":"##ticket.category##",
"Requesters":"##ticket.authors##",
"Description":"##ticket.content##"
}
```

**Comment by ericferon** [comment]
Hi,
As explained in https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400, this error is sent by the server connected to the webhook.
Without knowledge of your configuration, I cannot solve your problem.
You should examine the HTTP request sent to your server : is the body malformed ?
If yes, inform me about what is malformed.
K.r,

**Comment by RogueSnipa** [comment]
Yes, I think the body is malformed. But I do not know how to find out what exactly is wrong.
In my first message, the target server was [n8n webhook trigger node](https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.webhook/). Here is the response message that is logged in \files\webhook.log when it is sent to n8n:
```
2023-03-03 14:04:57 [905@GlpiServerName]
Error: call to URL http://My_n8nServerUrl/webhook-test/b1078922-c2ec-4cff-aac6-287334bfac46 failed with status 400, response <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Bad Request</pre>
</body>
</html>
, curl_error , curl_errno 0
```
If I use [JSON formatter integration](https://zulip.com/integrations/doc/json) in Zulip chat server as the target server, the following is logged in the log:
```
2023-03-04 11:03:37 [8@GlpiServerName]
Error: call to URL https://MyZulipServerUrl/api/v1/external/json?api_key=myapikey failed with status 400, response {"result":"error","msg":"Malformed JSON","code":"INVALID_JSON"}
```

Is it possible to add the payload sent by the plugin to the webhook.log?

**Comment by ericferon** [comment]
Hi,
The HTTP headers and payload will be added in v1.0.11.
K.r,

**Comment by RogueSnipa** [comment]
Hi!
After upgrading to version 1.0.11, I see in the log that the JSON is incorrect due to a new line in the description field.
`##ticket.content##` placeholder returns multiline value.

```
2023-03-07 15:26:30 [8@GlpiServerName]
Error: call to URL https://MyZulipServerUrl/api/v1/external/json?api_key=myapikey failed with status 400, response {"result":"error","msg":"Malformed JSON","code":"INVALID_JSON"}
, curl_error , curl_errno 0
HTTP Headers : Array
(
    [0] => Content-type: application/json
)

POST Content : {
"ID": "0007841",
"Events":"Update of a Ticket",
"Locations":"MyTestLocation",
"Room Number":"LocationRoom",
"Title":"TestTopic",
"Category":"MyTestCategory",
"Requesters":"Username",
"Description":"<p>1</p>
<p>21</p>"
}
```

**Comment by ericferon** [comment]
Hi,
I think that you can easily handle this JSON content problem, according to https://stackoverflow.com/questions/42068/how-do-i-handle-newlines-in-json.
K.r,

**Comment by RogueSnipa** [comment]
Thank you so much for your time!
After I removed my changes in `\glpi\src\NotificationTargetTicket.php ` and applied your changes to `webhook\inc\notificationeventwebhook.class.php ` after the message sending event is triggered, I get a white screen. The following events are also recorded in the `\glpi\files\_log\php-errors.log`: "12".
```
[2023-03-12 22:23:14] glpiphplog.WARNING:   *** PHP Warning (2): Use of undefined constant data - assumed 'data' (this will throw an Error in a future version of PHP) in D:\WebServer\data\htdocs\glpi\src\NotificationTargetTicket.php at line 164
  Backtrace :
  src\NotificationTargetCommonITILObject.php:1024    NotificationTargetTicket->getDataForObject()
  src\NotificationTarget.php:1334                    NotificationTargetCommonITILObject->addDataForTemplate()
  ...hook\inc\notificationeventwebhook.class.php:145 NotificationTarget->getForTemplate()
  src\NotificationEventAbstract.php:85               PluginWebhookNotificationEventWebhook::extraRaise()
  src\NotificationEvent.php:187                      NotificationEventAbstract::raise()
  src\Ticket.php:1726                                NotificationEvent::raiseEvent()
  src\CommonDBTM.php:1727                            Ticket->post_updateItem()
  front\ticket.form.php:84                           CommonDBTM->update()
  
[2023-03-12 22:23:14] glpiphplog.WARNING:   *** PHP Warning (2): Illegal string offset '##ticket.description##' in D:\WebServer\data\htdocs\glpi\src\NotificationTargetTicket.php at line 164
  Backtrace :
  src\NotificationTargetCommonITILObject.php:1024    NotificationTargetTicket->getDataForObject()
  src\NotificationTarget.php:1334                    NotificationTargetCommonITILObject->addDataForTemplate()
  ...hook\inc\notificationeventwebhook.class.php:145 NotificationTarget->getForTemplate()
  src\NotificationEventAbstract.php:85               PluginWebhookNotificationEventWebhook::extraRaise()
  src\NotificationEvent.php:187                      NotificationEventAbstract::raise()
  src\Ticket.php:1726                                NotificationEvent::raiseEvent()
  src\CommonDBTM.php:1727                            Ticket->post_updateItem()
  front\ticket.form.php:84                           CommonDBTM->update()
  
[2023-03-12 22:23:14] glpiphplog.WARNING:   *** PHP Warning (2): Use of undefined constant String - assumed 'String' (this will throw an Error in a future version of PHP) in D:\WebServer\data\htdocs\glpi\plugins\webhook\inc\notificationeventwebhook.class.php at line 153
  Backtrace :
  src\NotificationEventAbstract.php:85               PluginWebhookNotificationEventWebhook::extraRaise()
  src\NotificationEvent.php:187                      NotificationEventAbstract::raise()
  src\Ticket.php:1726                                NotificationEvent::raiseEvent()
  src\CommonDBTM.php:1727                            Ticket->post_updateItem()
  front\ticket.form.php:84                           CommonDBTM->update()
  
[2023-03-12 22:23:14] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function raw() in D:\WebServer\data\htdocs\glpi\plugins\webhook\inc\notificationeventwebhook.class.php at line 153
  Backtrace :
  src\NotificationEventAbstract.php:85               PluginWebhookNotificationEventWebhook::extraRaise()
  src\NotificationEvent.php:187                      NotificationEventAbstract::raise()
  src\Ticket.php:1726                                NotificationEvent::raiseEvent()
  src\CommonDBTM.php:1727                            Ticket->post_updateItem()
  front\ticket.form.php:84                           CommonDBTM->update()
```

**Comment by ericferon** [comment]
Hi,
Can you replace, in the 2 lines 149 and 151
String.raw($data) 
by 
$data.replace(/\n/g, "\\\\n").replace(/\r/g, "\\\\r").replace(/\t/g, "\\\\t")
?
K.r,

**Comment by RogueSnipa** [comment]
I changed
`$content = NotificationTemplate::process($template_datas['content_text'], $data);`
to
`$content = NotificationTemplate::process($template_datas['content_text'], $data.replace(/\n/g, "\\n").replace(/\r/g, "\\r").replace(/\t/g, "\\t"));`

have this in `\glpi\files\_log\php-errors.log`
```
[2023-03-13 17:07:23] glpiphplog.CRITICAL:   *** Uncaught Exception ParseError: syntax error, unexpected '/' in D:\WebServer\data\htdocs\glpi\plugins\webhook\inc\notificationeventwebhook.class.php at line 149
  Backtrace :
  :                                                  glpi_autoload()
  src\QueuedNotification.php:549                     spl_autoload_call()
  src\QueuedNotification.php:590                     QueuedNotification::getPendings()
  src\CronTask.php:1018                              QueuedNotification::cronQueuedNotification()
  front\cron.php:64                                  CronTask::launch()
```

**Comment by ericferon** [comment]
Sorry for my mistake : 
In fact, the original 4 lines (148-151) can be kept. But a 5th line should be added : 
>if (isset($template_datas['content_text']) && !empty($template_datas['content_text']))
$content = NotificationTemplate::process($template_datas['content_text'], $data);
else
$content = NotificationTemplate::process($template_datas['content_html'], $data);
$content = str_replace(['\n', '\r', '\t'], ['\\\\n', '\\\\r', '\\\\t'], $content);
K.r,

**Comment by RogueSnipa** [comment]
I apologize for being slow with the answer.

This code (i replace in first array `'` to `"`)
`$content = str_replace(["\n", "\r", "\t"], ['\\n', '\\r', '\\t'], $content);`
 is not working. Because it changes the newline characters in all payload and this breaks it.
```
2023-03-16 10:52:06 [8@n8nserver]
Error: call to URL http://n8nserverurl/webhook/1f1048e0-87dd-44ac-be37-b768f099fafe failed with status 400, response <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Bad Request</pre>
</body>
</html>
, curl_error , curl_errno 0
HTTP Headers : Array
(
    [0] => Content-type: application/json
)

POST Content : {\r\n"ID": "0007841",\r\n"Events":"Update of a Ticket",\r\n"Locations":"MyTestLoc",\r\n"Room Number":"000 404",\r\n"Title":"TestTopic",\r\n"Category":"TestCat",\r\n"Requesters":"TestUser",\r\n"Description":"<p>1 <em>Text</em> 'Text'</p>\n<p>2 <strong>BoldText<br></strong></p>"\r\n}
```

Using code (I removed the tab symbol because the user simply cannot use it when editing text in GLPI)
`$content = str_replace(["\n", "\r"], ['', ''], $content);`
**the payload is not damaged**. 

But I'm sure there's another problem. If the user uses the double quotation mark in the ticket title (##ticket.title##) or in the ticket description (##ticket.content##, ##ticket.description##") , this also breaks the payload. And replacing all the double quotation marks in the entire payload will not solve this problem.

Example of replacement all double quotation mark in payload
```
POST Content : {'ID': '0007841','Events':'Update of a Ticket','Locations':'MyTestLoc','Room Number':'000 404','Title':'TestTopic 'QuotedWord'','Category':'TestCat','Requesters':'TestUser','Description':'<p>1 <em>Text</em> 'Text'</p><p>2 <strong>BoldText<br></strong></p>'}
```
![image](https://user-images.githubusercontent.com/78896767/225577500-45c0223f-e469-49d5-af76-66ed59196f65.png)

Example of replacement only in ticket topic and decription:
```
POST Content : {"ID": "0007841","Events":"Update of a Ticket","Locations":"MyTestLoc","Room Number":"000 404","Title":"TestTopic 'QuotedWord'","Category":"TestCat","Requesters":"TestUser","Description":"<p>1 <em>Text</em> 'Text'</p><p>2 <strong>BoldText<br></strong></p>"}
```
![image](https://user-images.githubusercontent.com/78896767/225579963-6a38d8b5-8c51-425a-928a-bcbcc73b2253.png)

**Comment by ericferon** [comment]
Hi,
Can you download the last committed file inc/notificationeventwebhook.class.php and test it ?
It should escape the CR/LF/TAB characters, as the quote according to the one used as delimiter in the template.
K.r,

**Comment by RogueSnipa** [comment]
Hi!
I tested a new one `inc/notificationeventwebhook.class.php`. It works fine when I replaced the quotation marks around the regex in lines 144 and 162 with a double quotation mark (without this, the replacement does not work).

In line 162, it is unnecessary to replace with four backslashes. Two give the desired result.
`$data = str_replace(["\n", "\r", "\t"], ['\\n', '\\r', '\\t'], $data);`
In general, I think that you need to change the newline character to nothing. In the program, the User cannot put either a tab sign or a line break in the editable fields.
The problematic newline sign (\n) is added by the GLPI itself to make the html code human-readable in the "Source code" window.

Testing revealed another problem: an odd number of consecutive backslashes also break payload.
```
