### ISSUE TITLE
Passing Parameters in url request

### ISSUE THREAD

**Issue by cchazalet** [ericferon/glpi-webhook#16]
Is it possible to specify parameters in the query to execute the following command ? 

```
curl -X POST JENKINS_URL/job/JOB_NAME/build \
  --user USER:TOKEN \
  --data-urlencode json='{"parameter": [{"name":"id", "value":"123"}, {"name":"verbosity", "value":"high"}]}'
```

In fact I want to build a jenkins job by passing glpi variables as parameters

Thank you in advance for your help,

Have a nice day

**Comment by ericferon** [comment]
Hi,
Currently, glpi variables mentioned in the url as parameters would not be replaced by their current values.
This would be an enhancement that I can add in a next version.
K.r,
