### ISSUE TITLE
Сomment information is not added to webhook data 

### ISSUE THREAD

**Issue by strelez13** [ericferon/glpi-webhook#19]
Сomment information is not added to webhook data 
GLPI 10.0.7 
Webhooks Version: 1.0.12  
  "chat_id": "string",
  **"comment": "##FOREACH LAST 1 timelineitems## ##timelineitems.description####ENDFOREACHtimelineitems##",** 
  "status": "##ticket.status##",
  "title": "##ticket.title##",
  "category": "##ticket.category##",
  "entity": "##ticket.shortentity##",
  "author": "##ticket.authors##",
  "description": "##ticket.description##",
  "priority": "##ticket.priority##"
}

**Comment by miguelanruiz** [comment]
Hey, you could try separe instructions:
##timelineitems.description####ENDFOREACHtimelineitems##
##timelineitems.description## ##ENDFOREACHtimelineitems##
