### ISSUE TITLE
Dont accept tags LOOPS

### ISSUE THREAD

**Issue by mauriciomagalhaes** [ericferon/glpi-webhook#21]
Hi,

Does not accept GLPI loop tags, Some tags only work within other tags

Ex:
##FOREACHauthors## ##author.phone## ##ENDFOREACHauthors##

Returns empty

GLPI 10.0.7
Webhooks 1.0.12

**Comment by ericferon** [comment]
Hi,
I tested the webhook plugin with an existing template ("Tickets") and all the tags, including FOREACH ones, are replaced correctly.
So I cannot repeat your problem.
K.r,

**Comment by egorky** [comment]
I can confirm , loops are not working. The default Tickets template does not have a FOREACH

> Hi,
> 
> Does not accept GLPI loop tags, Some tags only work within other tags
> 
> Ex: ##FOREACHauthors## ##author.phone## ##ENDFOREACHauthors##
> 
> Returns empty
> 
> GLPI 10.0.7 Webhooks 1.0.12

I encountered the same problem, reading other issues  in this repository found out you have to write the begining and the ending of the loop on a line of its own. Like this:
##FOREACHauthors##
##author.phone##
##ENDFOREACHauthors##

**Comment by egorky** [comment]
@ericferon I can confirm Loops are not working. I tested the Tickets Template and nothing inside loops gets send to the API on the other side. 
Try this: Using exactly the same template but adding it to a notification as a email and as a webhook

<img width="863" alt="image" src="https://github.com/ericferon/glpi-webhook/assets/54412925/23f3ca8c-3a83-4eaa-a3fc-0a8056007f29">

Now, I fire up the notification making some change in my ticket, observe the difference between both channels.
The mail channel sends this:
<img width="295" alt="image" src="https://github.com/ericferon/glpi-webhook/assets/54412925/ba0f31c1-35e7-42d2-8760-a7b8d88670f5">

while the webhook sends this:

<img width="314" alt="image" src="https://github.com/ericferon/glpi-webhook/assets/54412925/7e1c4f7a-69e4-4be1-9fd7-7b741ee5d6d0">


As you can see, the loop that includes the computer does not work in the webhook. This loop is completly ignore (you can find it in the Tickets Template) :
##FOREACHitems##
 ##IFticket.itemtype##
  ##ticket.itemtype## - ##ticket.item.name##
  ##IFticket.item.model## ##lang.ticket.item.model## : ##ticket.item.model## ##ENDIFticket.item.model##
  ##IFticket.item.serial## ##lang.ticket.item.serial## : ##ticket.item.serial## ##ENDIFticket.item.serial##
  ##IFticket.item.otherserial## ##lang.ticket.item.otherserial## : ##ticket.item.otherserial## ##ENDIFticket.item.otherserial##
 ##ENDIFticket.itemtype##
##ENDFOREACHitems##
