### ISSUE TITLE
Does it work on GLPI version 10.0.9?

### ISSUE THREAD

**Issue by lucasrodri** [ericferon/glpi-webhook#22]
Does it work on GLPI version 10.0.9? 
How to create an entry in Setup>Webhooks configuration???

**Comment by ericferon** [comment]
Hi,
To my knowledge, it works on GLPI 10.0.9.
If you do not see the menu Setup->Webhooks configuration, check your profile : in the tab Webhooks Config, it must be granted for Read, Update or Create.
K.r,
