### ISSUE TITLE
Where to put it webhood id?

### ISSUE THREAD

**Issue by repentandliveholy** [ericferon/glpi-webhook#24]
Hello!

Where can I fine a "setub>webhook" mentioned in wiki?

Thanks

**Comment by ericferon** [comment]
Hi,
Probably have you to authorize for configuration in your profile.
After a screen refresh, the menu will appear.
K.r,

**Comment by repentandliveholy** [comment]
Thanks for answer. Yes, I authorised as a super-admin

пн, 18 сент. 2023 г. в 15:53, Eric Feron ***@***.***>:

**Comment by repentandliveholy** [comment]
[image: image.png]

пн, 18 сент. 2023 г. в 15:53, Eric Feron ***@***.***>:

**Comment by repentandliveholy** [comment]
But still can't see it...

**Comment by ericferon** [comment]
Hi,
Probably have you also to disconnect and log in again, to refresh your rights.
There are 2 paths to the webhook configuration : 
- Setup>Webhooks configuration
- Setup>Plugins : click on the "Configure" (wrench) icon of the Webhook tile
K.r,

**Comment by repentandliveholy** [comment]
Yes, I loged in again. 

1. this shows only number of tries etc
2. shows nothing..

**Comment by repentandliveholy** [comment]
[image: image.png]
[image: image.png]

[image: image.png]

[image: image.png]


вт, 19 сент. 2023 г. в 11:04, Eric Feron ***@***.***>:

**Comment by repentandliveholy** [comment]
still doesnt work ... may there is something else to do?

вт, 19 сент. 2023 г. в 13:06, Repent And Live Holy <
***@***.***>:

**Comment by repentandliveholy** [comment]
thaks. the problem was PROFILES - it was need to switch ON right for WH!

пт, 22 сент. 2023 г. в 12:51, Repent And Live Holy <
***@***.***>:
