### ISSUE TITLE
How to use conditional statements in the beginning of payload?

### ISSUE THREAD

**Issue by renanredel** [ericferon/glpi-webhook#25]
Hello,

Env: GLPI 10.0.9
Plugin: 1.0.14

I'm trying to send some notifications to Teams with one conditional at the beginning.
If the condition doesn't match, nothing will be sent to the webhook.

When I tried to send the payload below, I get the error of invalid JSON: 

```
##IFchange.urgency=0##
{
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "themeColor": "0076D7",
    "summary": "##change.title##",
    "sections": [{
        "activityTitle": "##change.title##",
        "activitySubtitle": "##change.content##",
        "facts": [{
            "name": "##lang.change.authors##",
            "value": "##IFchange.authors## ##change.authors## ##ENDIFchange.authors## ##ELSEchange.authors##--##ENDELSEchange.authors##"
        }, {
            "name": "##lang.change.creationdate##",
            "value": "##change.creationdate##"
        }, {
            "name": "##lang.change.status##",
            "value": "##change.status##"
        }, {
            "name": "##lang.change.impact##",
            "value": "##change.impact##"
        }, {
            "name": "##lang.change.content##",
            "value": "##change.content##"
        }],
        "markdown": true
    }],
    "potentialAction": [{
        "@type": "OpenUri",
        "name": "Learn More",
        "targets": [{
            "os": "default",
            "uri": "https://glpi.url.com/front/change.form.php?id=##change.id##"
        }]
    }
    ]
}
##ENDIFchange.urgency##
```

Error:

`Error: call to URL
ttps://domain.webhook.office.com/webhookb2/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/IncomingWebhook/XXXXXXXXXXXXXXXXXXXXXXXxx failed with status 400, response Invalid webhook request - Empty Payload, curl_error , curl_errno 0`

How can I use this conditional statements in the JSON payload ?

**Comment by ericferon** [comment]
Hi,
As mentioned in the error message, there is a problem with your payload and I cannot debug your payload.
You can find a bit more information in a log file called "webhook.log", in the directory files>_log on your web server.
Using curl or postman, you can send yourself the same HTTP request.
You can send a simple payload first, and increase its complexity gradually.
K.r,
