### ISSUE TITLE
Can't find 

### ISSUE THREAD

**Issue by rogerzero** [ericferon/glpi-webhook#26]
Is there any step i'm missing? Cause i can't find Config > Webhooks on my setup.

<img width="472" alt="image" src="https://github.com/ericferon/glpi-webhook/assets/23318078/9651999d-5c13-4d60-90a8-3d3e01123def">

I'm using your latest version

**Comment by ericferon** [comment]
Hi,
Please, see the solution in issue #24.
K.r,
