### ISSUE TITLE
Setup portion is not shown in GLPI menu

### ISSUE THREAD

**Issue by opex13** [ericferon/glpi-webhook#29]
Hi,

After installation of plugin via marketplace link to setup seems to be broken.
Configure link from plugin details is (your_enviroment_name)/marketplace/webhook/front/config.php, but this seems to be a blank page, and no option webhook configuration in Setup menu:
![image](https://github.com/ericferon/glpi-webhook/assets/97477580/aeb62a28-1512-4d79-8f68-17f953bc7fd9)
Plugin version is 1.0.14, GLPI version is 10.0.5

**Comment by ericferon** [comment]
Hi,
Probably do you need to grant your profile (even super-admin) to access the plugin's configuration (menu Administration->Profiles->yourProfile->Webhooks Config).
K.r,

**Comment by opex13** [comment]
Confirmed! 
thanks.
