### ISSUE TITLE
"Webhooks configuration" button in GLPI does not shows off

### ISSUE THREAD

**Issue by isaacvicente** [ericferon/glpi-webhook#31]
I decompressed and installed the plugin in my GLPI instance. I enabled it as well.
But, when following the wiki, the "Setup > Webhooks configuration" does not shows off.

I don't know why and I did a lot of research trying to make it work, but I couldn't find anything.

Here's the "Plugins" page:

![Captura de tela de 2023-10-18 16-23-33](https://github.com/ericferon/glpi-webhook/assets/77455425/91ba8f7f-98bb-4f1a-bc53-0efc9cbc24cc)

Here's the options ("Configurar" stands for "Setup" in Portuguese):

![Captura de tela de 2023-10-18 16-24-23](https://github.com/ericferon/glpi-webhook/assets/77455425/177efc54-5f43-4e5a-b56f-0a4d8b04d78a)

If you guys could help me I would really appreciate it.

**Comment by ericferon** [comment]
Hi,
Have a look to issue #29 .
K.r,

**Comment by isaacvicente** [comment]
Thank you very much!!
