### ISSUE TITLE
Configuration not showing

### ISSUE THREAD

**Issue by charliegregorio** [ericferon/glpi-webhook#32]
I install plugin using marketplace and enable plugin. After i click in configure e in next screen configuration is blank screen.
![image](https://github.com/ericferon/glpi-webhook/assets/148587454/7aeda34e-2be8-4190-8646-702ccff55171)
![image](https://github.com/ericferon/glpi-webhook/assets/148587454/f8762591-c326-45e2-9975-57ea194f45d5)
My version is
![image](https://github.com/ericferon/glpi-webhook/assets/148587454/8bf83bb8-406a-4c86-96d7-4d8e9856b34b)

**Comment by ericferon** [comment]
Hi,
Probably is it the same cause as issue #29 : you need to grant access to configuration into your profile.
K.r,
