### ISSUE TITLE
 Not all Notification Tags are working

### ISSUE THREAD

**Issue by egorky** [ericferon/glpi-webhook#33]
Hi , wonderful project. 
I have it working on my GLPI 10.0.9 and notifications works fine but I have noticed that authors and actors loops are not working. For example, if I use:
##FOREACHactors## ##actor.itemtype## ##actor.mobile##  ##actor.name## ##ENDFOREACHactors##
I get an empty payload, But if I use the exact same notification template with a mail notification, the actors appear with no problem. (Yes, I know I have to use { } for the payload and I am using them, this is just an example)

This leads to believe that this webhook is not passing the FOREACH variables because the other variables work well.

 Can somebody help?

**Comment by egorky** [comment]
Reading other issues in this repository I found out you have to write the begining and the ending of the loop on a line of its own. Like this:
##FOREACHauthors##
##author.phone##
##ENDFOREACHauthors##

closing, thanks

**Comment by egorky** [comment]
same as issue 21 [https://github.com/ericferon/glpi-webhook/issues/21](url)

**Comment by egorky** [comment]
Maybe this is not the problem, but one can notice this Notification Target it is not declared in the file setup.php: NotificationTargetCommonITILObject

**Comment by ericferon** [comment]
Hi,
Thank you for the hint.
I modified the target list in v1.0.15.
Can you have a try and confirm that it solves this issue ?
Thanks in advance,

**Comment by egorky** [comment]
Thanks @ericferon , but is not working yet. Must be something else that is missing. And I see other people are reporting the same issue with the FOREACH routines. 
The notification vía email sent this:
<img width="410" alt="image" src="https://github.com/ericferon/glpi-webhook/assets/54412925/879afe03-0a22-4211-8329-8a769b1cd63c">
the notification vía webhook sent:
<img width="430" alt="image" src="https://github.com/ericferon/glpi-webhook/assets/54412925/5987515b-6e05-4955-9380-894380d5dc6e">
I am using the exact same Notification Template in both cases.
<img width="533" alt="image" src="https://github.com/ericferon/glpi-webhook/assets/54412925/d6de2cdc-f409-4b09-b484-6bb5533b103d">

**Comment by ericferon** [comment]
Hi,
Fixed in v1.0.16.
K.r,

**Comment by egorky** [comment]
thanks @ericferon , I can confirm that the last update solved the issue. Many thanks!
