### ISSUE TITLE
FOREACH doesnt work

### ISSUE THREAD

**Issue by repentandliveholy** [ericferon/glpi-webhook#34]
Hello! How can I use FOREACH with webhooks plugin?
Actually, I need to send tasks to telegram, but it doesnt work with "curl error" every time or it just send ##task.description## (literaly)
Thanks

**Comment by ericferon** [comment]
Hi,
FOREACH is normally working with the plugin (the plugin uses the same template parser as the email notifications, f.i)
Often, if one variable isn't substituted by a value, that means that the variable doesn't exist.
The best way is to test your request manually with curl or postman. Then, to replicate the behaviour in the plugin.
K.r,

**Comment by repentandliveholy** [comment]
Thanks, I'll try.
