### ISSUE TITLE
Debug data

### ISSUE THREAD

**Issue by HydrelioxGitHub** [ericferon/glpi-webhook#35]
This is more a question than an issue. Please point at me where I can ask if this not the appropriate place.

I would like to debug Json message send by Glpi because I have not the same result when I trigger webhook notification and directly make a request with the same Json.

Is there logs somewhere or a debug mode so I can track very accurately what is send from GLPI.

Thank you for your work, your time and your skill. It really enhance our work.

**Comment by egorky** [comment]
Just point your webhook to [webhook](https://webhook.site/) , you can send anything over there

**Comment by ericferon** [comment]
Hi,
The file files/_log/webhook.log contains the sent headers and body, but only when the HTTP return code is different from 200 or 201.
There is no debug mode.
But with the egorky's suggestion, you can get the same result, I guess.
K.r,

**Comment by HydrelioxGitHub** [comment]
Thanks for your suggestions, I'll try these as soon as possible.

**Comment by ericferon** [comment]
Hi,
I added a debug mode, in v1.0.17.
K.r,
