### ISSUE TITLE
Webhook version 1.0.17 won't install

### ISSUE THREAD

**Issue by raregtp** [ericferon/glpi-webhook#36]
Tried upgrading my install from 1.0.16 to 1.0.17, but the "upgrade" never finishes and just asks me to upgrade again.  Doing this from within the Marketplace, and running GLPI 10.0.10.  Manually removed the Webhook plugin as there was no uninstall option.  After removing, was able to clean the plugin, and then attempted a new install of 1.0.17, with no change.  After installing, refreshing the Marketplace just shows the folder with a +....clicking it makes it look as though it's installing, but afterwards refreshing the Marketplace page still shows the same status.  Rinse and repeat.

Please let me know if you need more info or need anything else attempted.  Thanks!

**Comment by rafael-menezes-truechange** [comment]
Same problem here. After clicking the update button, it just disappears and doesn't show the "enable" button, making the plugin completely disabled. Also worth of note that it shows in the newest version, but even still, asks for an update.

![image](https://github.com/ericferon/glpi-webhook/assets/148118448/c3e98f15-3a70-45d3-b015-c9a7d2ebbe3c)

**Comment by raregtp** [comment]
Thanks @rafael-menezes-truechange I should have included a screenshot!

**Comment by egorky** [comment]
I had the exactly same problem, so what I did was uninstalled the module from the marketplace and installed it in the plugins directory via CLI. It is exactly the same.

**Comment by ericferon** [comment]
Hi,
Indeed, there was a bug in the installation process.
Solved in v1.0.18.
K.r,

**Comment by raregtp** [comment]
Thanks...I can confirm that v1.0.18 resolves the issue.  Appreciate the quick turn-around!
