### ISSUE TITLE
Unable to Add New Webhook Configuration in GLPI Webhook Plugin

### ISSUE THREAD

**Issue by Claonilton** [ericferon/glpi-webhook#40]
Hello,

I am experiencing an issue with the GLPI Webhook plugin. I am attempting to add a new webhook configuration to integrate GLPI with external services, but I am unable to do so.

Issue Details:

Page URL: marketplace/webhook/front/config.php
Expected Behavior: There should be an "Add" or "Insert" button on the webhook configuration page to allow for the creation of new webhook entries.
Actual Behavior: The page does not display any option to add or insert a new webhook configuration. This prevents the creation of new webhooks.
Steps to Reproduce:

Navigate to the webhook configuration page at marketplace/webhook/front/config.php.
Observe the lack of an "Add" or "Insert" button to create a new webhook.
Possible Causes:
 
Environment:

GLPI Version: 10.0.10
Webhook Plugin Version: 1.0.18 

Thank's

![image](https://github.com/ericferon/glpi-webhook/assets/16517344/59f4905d-af61-49f8-a72b-d52696601968)

**Comment by Claonilton** [comment]
![image](https://github.com/ericferon/glpi-webhook/assets/16517344/08e835bc-bcc1-45d9-8b36-255c1084a374)

**Comment by ericferon** [comment]
Hi,
Do you get error messages linked to this operation in files/_log/php-errors.log ?
K.r,

**Comment by kocmo790** [comment]
Hi! I get same bug if i login by SuperAdmin. But If I login by any account with all right (<profile> - Webhook Config - Configuration) - all ok!
