### ISSUE TITLE
Error 400 with Ms teams

### ISSUE THREAD

**Issue by urbantao** [ericferon/glpi-webhook#46]
Hi,

I got an issue using webhook plugin into glpi 10.14 with Teams channel. I follewd the webhook wiki step-by-step for the configuration and now I got this error :

Error : call to URL https://montenant.webhook.office.com/webhookb2/b34a3f0f-045b-4276-bf50-14f45269039e@25b4356d5-b067-455c-a78d-9e6b83626a69/IncomingWebhook/e7e2f1222a9f44b1995d0f034ed17eaa/d57fe641-c15d-4ac9-89fa-58c56b4a1444 failed with status 400, response Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: a. Path '', line 0, position 0., curl_error , curl_errno 0
HTTP Headers : Array

On this I got no authentication required.

Thx for your helps

**Comment by ericferon** [comment]
Hi,
You can activate the debug mode for your webhook entry, in the main configuration form.
You will find the result in files/_log/webhook.log.
You should then have the elements to use curl or Postman to test which character is unexpected.
K.r,
