### ISSUE TITLE
failed with status 0, response , curl_error SSL certificate problem: self-signed certificate in certificate chain, curl_errno 60

### ISSUE THREAD

**Issue by glionel** [ericferon/glpi-webhook#48]
HI.

When posting a new ticket, GLPI returns an error message:
Error: call to URL https://*********** failed with status 0, response , curl_error SSL certificate problem: self-signed certificate in certificate chain, curl_errno 60

![image](https://github.com/ericferon/glpi-webhook/assets/12128907/2f4c3694-a5c5-4210-8f80-15c65aff5e07)

Thanks for your help.

**Comment by ericferon** [comment]
Hi,
This is a certificate problem.
Try to solve it by repeating manually the HTTP requests sequence that Webhook sends. You can get them by activating the debug mode in your webhook configuration and reading the files/_log/webhook.log.
K.r,
