### ISSUE TITLE
webhook doesnt not work with mattermost

### ISSUE THREAD

**Issue by sireskandar** [ericferon/glpi-webhook#6]
i follow you guide but doesn't seem to work, if i do curl from server itself it works

**Comment by ericferon** [comment]
A new version is just released, fixing a bug.
Maybe your solution is in there.
K.r,

**Comment by sireskandar** [comment]
does it need to put username and secret key as well ??

**Comment by ericferon** [comment]
Maybe.
It depends on the authentication method requested by Mattermost APIs.
I don't use this tool ; so, I cannot help you precisely.
The plugin is working with Jira, Confluence and Slack. If Mattermost is working in a similar way, it should work also.
K.r,

**Comment by sireskandar** [comment]
curl -X POST -H 'Content-type: application/json' --data '{"text":"New Ticket"}' http://mattermost.omens-studios.com/hooks/kx6xp4ebt7yhjckiaxskg7s63h

i want to make webhook work in the above form, i have followed your guide from wiki but seems all not working.

![image](https://user-images.githubusercontent.com/26816348/193523721-49725d26-fd18-4e7e-ac9b-b24b12df4dc3.png)
![image](https://user-images.githubusercontent.com/26816348/193523853-64687f64-58da-4ff7-8e95-39748c33b2e3.png)
![image](https://user-images.githubusercontent.com/26816348/193523965-116abf41-b653-45bb-bb22-9be6c252b8bc.png)
![image](https://user-images.githubusercontent.com/26816348/193524109-f0329a7b-13b2-4b31-a8e5-1d2bcd6b1bd2.png)


i
