### ISSUE TITLE
Mattermost Not Working Webhook

### ISSUE THREAD

**Issue by sireskandar** [ericferon/glpi-webhook#7]
curl -X POST -H 'Content-type: application/json' --data '{"text":"New Ticket"}' http://mattermost.xxx/hook/xxx

i want to make webhook work in the above form, i have followed your guide from wiki but seems all not working.

![image](https://user-images.githubusercontent.com/26816348/193525293-4cf805f4-163f-4894-8ca5-ffb6dc86a2cf.png)

![image](https://user-images.githubusercontent.com/26816348/193523853-64687f64-58da-4ff7-8e95-39748c33b2e3.png)
![image](https://user-images.githubusercontent.com/26816348/193523965-116abf41-b653-45bb-bb22-9be6c252b8bc.png)
![image](https://user-images.githubusercontent.com/26816348/193524109-f0329a7b-13b2-4b31-a8e5-1d2bcd6b1bd2.png)

**Comment by ericferon** [comment]
Hi,
"Authentication Type" field should be "1 - None".
K.r,

**Comment by sireskandar** [comment]
![image](https://user-images.githubusercontent.com/26816348/194222498-b26dd08c-e24f-406e-8afc-63e49abcf152.png)

i dont see any option on the auth type as " NONE "

**Comment by ericferon** [comment]
It has been added in v1.0.4.
K.r,
