### ISSUE TITLE
No Webhook in Recipients

### ISSUE THREAD

**Issue by SergPV** [ericferon/glpi-webhook#9]
Hi,
I'm trying to set up the webhook as described in the wiki. In the last point, I need to choose the recipient. But I don't have webhook options in the list.
![WebHookNotification](https://user-images.githubusercontent.com/23650666/195907568-3d950059-c3e7-431f-bcdc-1d5f0be6a2e1.jpg)

**Comment by ericferon** [comment]
Hi,
You show the top of the recipients list. Normally, the webhook recipients are at the bottom of the list.
K.r,

**Comment by SergPV** [comment]
I know. Unsuccessful screenshot. But there is nothing below either.
![WebHookNotification2](https://user-images.githubusercontent.com/23650666/195999439-1bf72457-5396-4096-bbc7-00fb0110efa8.jpg)

**Comment by ericferon** [comment]
Hi,
Have you error messages related to the plugin into pathtoglpi/files/_log/php-errors.log or sql-errors.log ?
Otherwise, can you read the table glpi_plugin_webhook_configs in the GLPI database and execute the query "SELECT id, name FROM glpi_plugin_webhook_configs" ?
K.r,

**Comment by RogueSnipa** [comment]
I also have the same problem. I have no related errors in `/files/_log/php-errors.log` or `sql-errors.log`. There is only one row in the `glpi_plugin_webhook_configs` table:
|id|name|
|--|----|
|1|ZTest|

**Comment by SergPV** [comment]
I have no related errors in **php-errors.log** or **sql-errors.log**

**glpi_plugin_webhook_configs** table:
<html>
<body>


id | name
-- | --
1 | TestHook


</body>
</html>

**Comment by ericferon** [comment]
There was indeed a bug, that has been fixed in v1.0.6.
K.r,
